// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HighSchoolClass
{
    internal sealed partial class Vsix
    {
        public const string Id = "HighSchoolClass.7591c91c-93f7-46d1-954f-28a527fd3c5b";
        public const string Name = "HighSchoolClass";
        public const string Description = @"C# Class meant for high school....private attributes with GetZZZ and SetZZZ for each attribute...C# Class for ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Siemens Digital Industries Software";
        public const string Tags = "";
    }
}
